name: SpigotSuite
main: com.hjjg200.spigotSuite.SpigotSuite
version: 0.1
api-version: 1.16
# Enable when server starts up
load: STARTUP
commands:
  backup:
    description: Backup-related commands
    usage: /<command> <info>
