name: SpigotSuite
main: com.hjjg200.spigotSuite.SpigotSuite
version: 0.1
api-version: 1.18
# Enable when server starts up
load: STARTUP
commands:
  backupinfo:
    description: Show information about backups
    usage: /<command> [all/size]
    aliases: [binfo]
    permission: spigotSuite
  backupchecksum:
    description: Evaluate entry-level file-only checksum for tar archive and if specified, compare it against current files
    usage: /<command> <tar_path> [plugins/resources/world <world_name>]
    aliases: [bcs, bchecksum, bsum]
    permission: spigotSuite
  backupoverride:
    description: Executes a force-full backup immediately
    usage: /<command>
    aliases: [boverride]
    permission: spigotSuite
permissions:
  spigotSuite:
    default: op
